added new color combinations
Bruddet/bruddet pull request #124
Opened 2024-07-18 07:58 UTC by MichelleGjolberg

## Endringstype.
- Ny funksjonalitet 

## Linke til oppgave (Notion).
https://www.notion.so/bekks/Bruk-fargepallett-fra-Nosleep-til-farger-for-bakgrunn-tekst-og-komponenter-956e8a9898f54ff3a031d5085f42e8fc?pvs=4
## Beskrivelse.
- Lagt til flere fargekombinasjoner  fra skisser/nosleep sitt pallet 
## Skjermbilder.
![Screenshot 2024-07-18 at 09 56 01](https://github.com/user-attachments/assets/e26c1a26-35b5-4ae1-8906-32fa5f4a2e78)

2024-07-18 11:28 UTC, emilaukner reviewed
Burde ikke text-color settes i container div på alle events/artikler istedetfor å passe de ned?

2024-07-19 07:45 UTC, annikensyvertsen commented on frontend/app/utils/colorCombinations.ts
> +    case "nightThemeBlueYellow":
Her tenker jeg at et alernativ til å ha så mange switchcaser som ligner så kan vi lage en liste som vi sjekker på.
F.eks: const demedsvartramme = ['daythemeblueblack', 'daythemepeachblue'...] osv
også kan man returnere farge basert på om den er i listen. Hvis det gir mening

2024-07-19 07:57 UTC, annikensyvertsen requested changes

2024-07-19 07:57 UTC, annikensyvertsen commented on cms/schemaTypes/objects/colorCombination.ts
> +  {title: 'Lys blå primær, sort sekundær', value: 'dayThemeBlueBlack', theme: 'day'},
kunne man gått så langt som å legge til fargene på objektene? Så slipper vi switchcaser og if-setninger senere?
type legge til bg-color-primary, bg-color-secondary osv. Ser for meg at vi kan fjerne mye kode da!

2024-07-19 07:57 UTC, annikensyvertsen commented on frontend/app/utils/colorCombinations.ts
> +    case "nightThemePurpleWhite":
Her tenker jeg at et alernativ til å ha så mange switchcaser som ligner så kan vi lage en liste som vi sjekker på.
F.eks: const svarttekst= ['daythemeblueblack', 'daythemepeachblue'...] osv (med et annet variabelnavn)
også kan man returnere farge basert på om den er i listen. Hvis det gir mening.
Dette blir sikkert ikke relevant hvis vi følger det jeg skrev i kommentaren over.

2024-07-22 05:59 UTC, annikensyvertsen commented on cms/schemaTypes/objects/colorCombination.ts
> +export const COLORCOMBINATION: ColorCombination[] = [
burde hete 'colorcombinations'

2024-07-22 05:59 UTC, annikensyvertsen commented on cms/schemaTypes/objects/colorCombination.ts
> +export const colorCombinationDay = {
denne burde også være i flertall

2024-07-22 06:00 UTC, annikensyvertsen commented on cms/schemaTypes/objects/colorCombination.ts
> +export const colorCombinationNight = {
flertall

2024-08-01 08:48 UTC, closed without merging